EVENT_MANAGER = require("tests/fake_event_manager")
SLASH_STUFF = require("tests/fake_slash_stuff")
ZO_Globals = require("tests/fake_zo_globals")

ut_helper = require("tests/ut_helper")

esoTERM = require("esoTERM")
esoTERM_char = require("esoTERM_char")
esoTERM_pve = require("esoTERM_pve")
esoTERM_pvp = require("esoTERM_pvp")
esoTERM_loot = require("esoTERM_loot")
esoTERM_init = require("esoTERM_init")
esoTERM_slash = require("esoTERM_slash")
esoTERM_window = require("esoTERM_window")
esoTERM_output = require("esoTERM_output")
